config/routes.rb
SweetSuite::Dialogue::Application.routes.draw do

  root :to => "rooms#index"

  # SweetSuite authentication callback
  match '/auth/sweetsuite/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'


  resources :rooms

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :room
  belongs_to :user
  
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base

  has_many :participations
  has_many :users, :through => :participations


  def to_s
    name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SweetSuite::Helpers
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    render
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_filter :authenticate_user!
  respond_to :html, :json

  def index
    @rooms = Room.all
    respond_with(@rooms)
  end

  def show
    @rooms = Room.all
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params[:room])
    if @room.save
      redirect_to @room
    else
      render :new
    end
  end




end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    session[:access_token] = auth_hash['credentials']['token']
    redirect_to root_url
  end
  
  def failure
  end

  private

  def auth_hash
    env['omniauth.auth']
  end

end

app/controllers/talk_controller.rb
require 'cramp'

Cramp::Websocket.backend = :thin

class TalkController < Cramp::Websocket

  unloadable


  on_start :say_hello
  on_data :listen
  on_finish :die


  def say_hello
    render "Hey there!\n"
  end

  def respond_with
    ['101 WebSocket Protocol Handshake',
      {'Content-type' => 'text/plain', 
       'sec-websocket-origin' => 'http://localhost:3000',
       'sec-websocket-location' => 'ws://localhost:3000/talk'}]
  end


  def listen(message)
    puts "heard: #{message}"
  end

  def die
    puts "Nuuuuuuuu! I r ded."
  end


end

app/controllers/talk_websocket.rb
=begin
Cramp::Websocket.backend = :thin

class TalkWebsocket < Cramp::Websocket

  include SweetSuite::Helpers

  unloadable


  on_start :say_hello
  on_data :listen
  on_finish :die


  def say_hello
    render "Hey there!\n"
  end

  def respond_with
    ['101 WebSocket Protocol Handshake',
      {'Content-type' => 'text/plain', 
       'sec-websocket-origin' => 'http://localhost:3000',
       'sec-websocket-location' => 'ws://localhost:3000/talk'}]
  end


  def listen(message)
    puts "heard: #{message}"

    render MultiJson.encode({'current_user' => current_user})
  end

  def die
    puts "Nuuuuuuuu! I r ded."
  end

  def session
    ActiveSupport::HashWithIndifferentAccess.new(@env['action_dispatch.request.unsigned_session_cookie'])
  end

end
=end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.haml
%h1 Hi!

= current_user['email']

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Dialogue : SweetSuite
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Cabin:bold', 'compiled/screen.css'
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.js','rails', 'underscore-min', 'handlebars', 'jellybean', 'application'
    = csrf_meta_tag
  %body
    #omnibar
      .brand Dialogue
      .currentUser
        = current_user.name
        = "(#{current_user.email})"
    #application
      = yield

app/views/rooms/index.html.haml
%section.leftSplit
  %ul#roomList
  %ul.actionsListView
    %li= link_to 'Create Room', new_room_path

%section#roomView

app/views/rooms/new.html.haml
%h1 Create Room

= semantic_form_for @room do |f|
  = f.inputs
  = f.buttons

app/views/rooms/show.html.haml
%section.roomList
  %ul.sectionedListView
    %li
      %h1 Active Rooms
      %ul
        - @rooms.each do |room|
          %li
            = link_to_unless_current room, room do 
              = link_to room, room, :class => 'selected'
    %li
      %h1 Recent Rooms
      %ul
        %li= link_to 'Envy Room'
        %li= link_to 'Sweet Chat'
    %li
      %h1 Smart Rooms
      %ul
        %li= link_to 'Recent Activity'
        %li= link_to 'Github Notifications'
  %ul.actionsListView
    %li= link_to 'Create Room', new_room_path

%section.roomView
  %hgroup.roomInfo
    %h1
      = @room.name
    %h2
      = @room.topic
  %section.messagesListView
    - time = Time.now
    - 30.times do |n|
      %article.messageView
        .user 
          = ['Andrew S.', 'Olivier L.', 'Zach N.'][n % 3]
        .body
          - messages = []
          - messages.push('This is a short message.')
          - messages.push('This is the message body, you think you are better than me?! '*3)
          = messages[n % 2]
        %ul.meta
          %li
            %time= l(time + n.minutes, :format => :short)
          %li= link_to 'Favorite' 
          %li= link_to 'Hide'

  = form_for :message, :html => {:class => 'newMessageView'} do |f|
    = f.text_area :content, :size => '60x2', :resizable => 'no'
    = f.submit 'Send'